[package]
name = "exfil"
version = "0.1.11"
authors = ["Mason Sipe <m-sipe@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
md2 = "0.9.0"
